apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
      version: v1
  template:
    metadata:
      labels:
        app: sample-app
        version: v1
    spec:
      containers:
        - name: sample-app
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=Hello from v1"
          ports:
            - containerPort: 5678
