apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incident-tracker
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Anagha-07/prod-k8s-gitops-observability.git
    targetRevision: HEAD
    path: manifests/incident-tracker
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
